#!/usr/bin/env bash
# Run H11V on the Mac the way it runs on the device.
#
#   tools/run_local.sh                 windowed 640x480, mid profile
#   tools/run_local.sh --profile=low   pick the graphics profile (low|mid|high)
#   tools/run_local.sh --fullscreen    as on the device
#   tools/run_local.sh --world=NAME    use/create a named world (default h11v_dev)
#   tools/run_local.sh --fresh         delete that world first
#
# Same game, same config, same resolution — the Mac is an emulator of the device,
# never a second platform with its own affordances. The one deliberate difference
# is the window: fullscreen on a laptop is a worse way to develop and tells you
# nothing extra, since the render size is identical either way.
#
# What this is NOT is a measurement. Frame rates here mean nothing:
# specification/ARCHITECTURE.md is explicit that the device is the truth, and
# Apple's GPU has no relationship to a VideoCore VII.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROFILE="mid"
FULLSCREEN=0
WORLD="h11v_dev"
FRESH=0

for arg in "$@"; do
	case "$arg" in
		--profile=*) PROFILE="${arg#*=}" ;;
		--fullscreen) FULLSCREEN=1 ;;
		--world=*) WORLD="${arg#*=}" ;;
		--fresh) FRESH=1 ;;
		-h|--help) sed -n '2,13p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
		*) echo "Unknown option: $arg (try --help)" >&2; exit 2 ;;
	esac
done

die() { echo "error: $*" >&2; exit 1; }
case "$PROFILE" in low|mid|high) ;; *) die "unknown profile '$PROFILE' (low|mid|high)" ;; esac

. "$ROOT/tools/luanti_path.sh" || true
[ "${LUANTI_MISSING:-1}" = "0" ] || die "Luanti is not installed — see specification/ROADMAP.md v0.1"

[ -f "$ROOT/games/h11v/game.conf" ] || die "no game at $ROOT/games/h11v"
[ -f "$ROOT/tools/device/minetest.conf" ] || die "no tools/device/minetest.conf"
[ -f "$ROOT/tools/device/device-$PROFILE.conf" ] || die "no tools/device/device-$PROFILE.conf"

# --- make the game visible to the engine -------------------------------------
#
# The engine has no --userdata flag: it finds games in its share path and its own
# user directory, and nowhere else. On macOS that directory is still the
# pre-rename "minetest" one, even on 5.17 — surprising enough to cost an hour if
# rediscovered, so it is detected rather than assumed. (docs/decisions.md)
USER_DIR="$HOME/Library/Application Support/luanti"
[ -d "$USER_DIR" ] || USER_DIR="$HOME/Library/Application Support/minetest"
mkdir -p "$USER_DIR/games"
LINK="$USER_DIR/games/h11v"

# A real directory where the link belongs is fatal, and silently so if unchecked.
# `ln -sfn` cannot replace a directory: it creates the link INSIDE it, as
# games/h11v/h11v, and exits 0 (reproduced on this macOS). The --gameid list
# guard below then still passes, because a stale copy of the game is itself a
# valid game named h11v — so the engine would load week-old code and every gate
# that runs through this script would be green about the wrong tree.
if [ -d "$LINK" ] && [ ! -L "$LINK" ]; then
	die "a real directory sits where the game link belongs:
  $LINK
It is a copy of the game, not a link to this checkout, and the engine would load
it instead of $ROOT/games/h11v. Move it aside or delete it, then re-run."
fi
ln -sfn "$ROOT/games/h11v" "$LINK" || die "cannot link the game into $USER_DIR/games"

if ! "$LUANTI" --gameid list 2>&1 | grep -qx 'h11v'; then
	die "the engine cannot see the h11v game.
Linked $ROOT/games/h11v -> $LINK, but --gameid list does not list it."
fi

WORLD_PATH="$USER_DIR/worlds/$WORLD"

if [ "$FRESH" = 1 ]; then
	# Say which of the two things happened. The old message announced a removal
	# unconditionally, which is how nobody noticed for a whole phase that there was
	# never anything there to remove (below).
	if [ -d "$WORLD_PATH" ]; then
		rm -rf "$WORLD_PATH"
		echo "==> removed world '$WORLD'"
	else
		echo "==> no world '$WORLD' to remove; it will be created"
	fi
fi

# --- assemble the config ------------------------------------------------------
#
# Base + profile, in that order so a later key wins — the same assembly the
# deploy does for the device, so what is seen here is what runs there.
CONF="$(mktemp -t h11v-local)"
trap 'rm -f "$CONF"' EXIT
{
	echo "# Generated by tools/run_local.sh — base + device-$PROFILE"
	cat "$ROOT/tools/device/minetest.conf"
	echo
	cat "$ROOT/tools/device/device-$PROFILE.conf"
	echo
	# The one deliberate divergence from the device, and why.
	if [ "$FULLSCREEN" = 0 ]; then
		echo "fullscreen = false"
	fi
} > "$CONF"

echo "==> H11V · profile '$PROFILE' · 640x480 · world '$WORLD'"
echo "    (frame rates here are not a measurement — the device is the truth)"

# No "$@" here, ever. The options above are this script's own — the loop that
# parses them does not consume them — and the engine aborts on any parameter it
# does not know: `Unknown command-line parameter "--profile=low"` followed by its
# whole option dump, which reads like a broken engine rather than a broken
# wrapper. Every documented invocation of this script failed that way until v0.9
# (review finding H2). A new flag belongs in the case block above, and its effect
# belongs in the generated config or in an explicit argument on this line.
# --world, NOT --worldname, and the difference is the whole reason this gate was
# worth anything. `--worldname` only SELECTS a world that already exists; it
# creates nothing. So every run of this script logged `World '<name>' not
# available` and silently fell back to the engine's default `worlds/world` — a
# world generated at some earlier mapgen, by some earlier commit. --fresh deleted
# a path that was never there and cheerfully said so.
#
# That made this the visible-change gate attesting to geometry no change had
# touched. It was caught in v0.9's review while checking the evidence for the
# mgv7_spflags pin: the run cited as proof the terrain still worked had drawn
# chunks persisted from before it. `--world <path>` is the creating form, and the
# engine's own --help says so.
exec "$LUANTI" \
	--config "$CONF" \
	--gameid h11v \
	--world "$WORLD_PATH" \
	--go
